### ISSUE TITLE
juju quickstart not working in charmbox:latest

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/charmbox#51]
It seems quickstart isn't usable in the default install of charmbox:latest (tried with Aug 19 box, but I know it's been this way for a couple weeks):

``` bash
$ juju quickstart
Traceback (most recent call last):
  File "/usr/bin/juju-quickstart", line 25, in <module>
    from quickstart import (
  File "/usr/lib/python2.7/dist-packages/quickstart/app.py", line 30, in <module>
    from quickstart import (
  File "/usr/lib/python2.7/dist-packages/quickstart/juju.py", line 47, in <module>
    class Environment(jujuclient.Environment):
AttributeError: 'module' object has no attribute 'Environment'

$ pip list | grep quick
juju-quickstart (2.2.4)

$ pip list | grep juju
juju-deployer (0.9.0)
juju-quickstart (2.2.4)
jujubundlelib (0.5.2)
jujuclient (0.53.2)

$ sudo pip install -U juju-quickstart
<blah blah>

$ pip list | grep juju 
juju-deployer (0.9.0)
juju-quickstart (2.2.4)
jujubundlelib (0.4.1)
jujuclient (0.50.3)

$ juju quickstart
<blah blah>
<success>
```

Looks like jujubundlelib and jujuclient needed a downgrade to be compatible with quickstart-2.2.4.

**Comment by lazypower** [comment]
Charmbox:latest now deploys a juju 2.0 environment.

There is work for a juju-1 tag coming from jujubox. This work will have to be done on that branch
