### ISSUE TITLE
Can't build charm in $JUJU_REPOSITORY

### ISSUE THREAD

**Issue by simonklb** [juju-solutions/charmbox#57]
Trying to build my local charm in the charmbox using the default $JUJU_REPOSITORY path isn't working since the Docker volumes gets mounted with root:root permissions.

```
$ charm build
build: Composing into /home/ubuntu
build: Destination charm directory: /home/ubuntu/builds/charmname
build: Please add a `repo` key to your layer.yaml, with a url from which your layer can be cloned.
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==2.1.4', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 676, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 519, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 469, in generate
    layers = self.fetch()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/builder.py", line 243, in fetch
    self.target_dir.makedirs_p()
  File "/usr/lib/python2.7/dist-packages/path.py", line 1222, in makedirs_p
    self.makedirs(mode)
  File "/usr/lib/python2.7/dist-packages/path.py", line 1215, in makedirs
    os.makedirs(self, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/ubuntu/builds/charmname'

$ ls -al $JUJU_REPOSITORY/builds
total 8
drwxr-xr-x  2 root   root   4096 Sep 22 11:58 .
drwxr-xr-x 10 ubuntu ubuntu 4096 Sep 22 11:59 ..
```

**Comment by mbruzek** [comment]
This has definitely worked before. @simonklb did you mount a builds directory when you run charmbox?

My alias includes this: `-v $HOME/workspace/charms/builds:/home/ubuntu/builds` and I think that makes the user own the directory.

**Comment by simonklb** [comment]
@mbruzek Yea you're right. However, in my case I was going to execute the tests on a clean machine where I didn't have a build environment from before. I think it still makes sense to fix it for empty dirs.

Up to you though!
